Add README.md
devfullcycle/fclx pull request #3
Opened 2023-04-21 14:23 UTC by dannevesdantas

Incluindo README.md contendo os principais comandos apresentados nas aulas.

2023-04-21 14:43 UTC, dannevesdantas commented
Não há alteração em código GO, somente a inclusão de dois README.md

2023-04-22 02:55 UTC, argentinaluiz requested changes

2023-04-22 02:55 UTC, argentinaluiz commented on chatservice/README.md
> +https://www.docker.com/products/docker-desktop/
Mude a instrução do uso do Docker Desktop para apenas Docker. O usuário pode usar qualquer distribuição do Docker de forma geral.

2023-04-22 02:55 UTC, argentinaluiz commented on README.md
> +[![FCLX - Backend for Frontend com Next.js](https://img.youtube.com/vi/eCPGup9Pa4s/0.jpg)](https://www.youtube.com/watch?v=eCPGup9Pa4s)
Maravilha! Acrescente também a aula do Keycloak para ficar completo.

Recomendo remover os links do vídeo do Youtube, porque no domingo eles não serão mais listados

2023-04-22 02:55 UTC, argentinaluiz commented on chatservice/README.md
> +No Windows, utilize sempre o terminal do Ubuntu com o WSL 2 para executar os comandos.
Acrescente a recomendação do WSL e Docker apontando para este tutorial: [https://github.com/codeedu/wsl2-docker-quickstart](https://github.com/codeedu/wsl2-docker-quickstart)

2023-04-22 02:56 UTC, argentinaluiz commented
Oi @dannevesdantas , tudo bem?

Poxa, muito obrigado pela PR, eu fiz a análise, realize a modificações e submeta novamente.

Grande abraço!!!

2023-04-22 04:53 UTC, dannevesdantas commented on chatservice/README.md
> +https://www.docker.com/products/docker-desktop/
Feito!

2023-04-22 04:56 UTC, dannevesdantas commented on README.md
> +[![FCLX - Backend for Frontend com Next.js](https://img.youtube.com/vi/eCPGup9Pa4s/0.jpg)](https://www.youtube.com/watch?v=eCPGup9Pa4s)
Feito!

2023-04-22 05:02 UTC, dannevesdantas commented on chatservice/README.md
> +No Windows, utilize sempre o terminal do Ubuntu com o WSL 2 para executar os comandos.
DONE!👍

2023-04-22 05:03 UTC, dannevesdantas commented
> Oi @dannevesdantas , tudo bem?
> 
> Poxa, muito obrigado pela PR, eu fiz a análise, realize a modificações e submeta novamente.
> 
> Grande abraço!!!

Top! Feito!

2023-04-22 12:37 UTC, argentinaluiz approved these changes

2023-04-22 12:37 UTC, merged